name: CI / Build & Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    environment: pypi
    permissions:
      id-token: write

    strategy:
      fail-fast: false 
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10.11"]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install cibuildwheel
          pip install git+https://github.com/STBrian/py3dst.git

      - name: Run tests
        run: pytest

      - name: Build wheels
        run: cibuildwheel --output-dir wheelhouse

      - name: Prepare dist directory
        run: |
          mkdir -p dist
          cp wheelhouse/*.whl dist/
          python -m build --sdist --outdir dist

      - name: Publish to PyPI
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: pypa/gh-action-pypi-publish@release/v1
