name: CI / Build & Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    # ← Declare the environment here, at the job level :contentReference[oaicite:1]{index=1}
    environment: pypi
    permissions:
      # Mandatory for OIDC trusted publishing :contentReference[oaicite:2]{index=2}
      id-token: write

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9, 3.10, 3.11]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install cibuildwheel

      - name: Run tests
        run: pytest

      - name: Build wheels
        run: cibuildwheel --output-dir wheelhouse

      - name: Publish to PyPI
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: pypa/gh-action-pypi-publish@release/v1
